
name: Docker

on:
  push:
#     branches: [ main ]
    branches: [ main, develop ]
  pull_request:
#     branches: [ main ]
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  ubuntu-focal:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install shellspec
        run: curl -fsSL https://git.io/shellspec | sh -s -- --yes

      - name: Run integration tests
        run: ~/.local/bin/shellspec --tag test
#         run: ~/.local/bin/shellspec --tag docker
