
name: macOS Catalina

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  macos-catalina:
    runs-on: macos-10.15
#     strategy:
#       matrix:
#         shells:
# #           - {shell: sh}
# #           - {shell: dash}
#           - {shell: bash}
# #           - {shell: ksh}
# #           - {shell: zsh}
#       fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upgrade brew
        run: brew upgrade

      - name: Install Docker and dependencies
        run: |  
          brew install docker docker-machine docker-compose coreutils
          docker-machine create --driver virtualbox default
          docker-machine env default
          eval "$(docker-machine env default)"
#          ${{ matrix.shells.shell }} eval "$(docker-machine env default)"

      - name: Install shellspec
        run:  curl -fsSL https://git.io/shellspec | sh -s -- --yes

      - name: Run unit tests
        run:  ~/.local/bin/shellspec --tag compose
#         run:  ${{ matrix.shells.shell }} ~/.local/bin/shellspec --shell "${{ matrix.shells.shell }}" --tag compose

      - name: Stop Docker daemon
        run:  docker-machine stop default
