name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shellspec
        run: curl -fsSL https://git.io/shellspec | sh -s -- --yes

      - name: Run unit tests
        run: /home/runner/.local/bin/shellspec
