
name: Ubuntu Focal Fossa

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  ubuntu-focal:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        shells:
          - {shell: dash,        package: dash}
          - {shell: bash,        package: bash}
          - {shell: busybox ash, package: busybox}
          - {shell: ksh,         package: ksh}
          - {shell: mksh,        package: mksh}
#           - {shell: posh,        package: posh}
          - {shell: yash,        package: yash}
#           - {shell: zsh,         package: zsh}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install shell packages
        run: sudo apt-get install -y ${{ matrix.shells.package }}

      - name: Install shellspec
        run: curl -fsSL https://git.io/shellspec | sh -s -- --yes

      - name: Run unit tests
        run: sudo ${{ matrix.shells.shell }} ~/.local/bin/shellspec
